### ISSUE TITLE
Add more descriptive displayNames for ScrollToHOC

### ISSUE THREAD

**Issue by newyork-anthonyng** [ganderzz/react-scroll-to#10]
When using the `ScrollToHOC`, this is what my React debugger showed:

![screen shot 2017-11-18 at 8 48 47 am](https://user-images.githubusercontent.com/14035529/32982699-7c89fbba-cc3d-11e7-9ecb-dcd63329afa7.png)

Notice the `undefined` display name.

I think we should update how we are handling the `displayNames` so that it looks like the below:
![screen shot 2017-11-18 at 8 49 12 am](https://user-images.githubusercontent.com/14035529/32982716-a86cb9d4-cc3d-11e7-9997-ad706e3cf50f.png)

Notice how there is no more `undefined` display name. Also, we didn't lose the display name of the original component which I wrapped. 

Let me know what you think, and I can create a Pull Request. I would use the same techniques shown in the [React docs](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging).

**Comment by ganderzz** [comment]
@newyork-anthonyng 

The more we can get rid of the <Undefined> components, the better. Feel free to create a PR!
