### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by ganderzz** [ganderzz/react-scroll-to#101]
Convert all Javascript to Typescript

**Comment by thisis-Shitanshu** [comment]
Hey @ganderzz  . If convenient to you, can I join in?
It's an cool project and I am looking for an opportunity to contribute. Also, I have worked on TypeScript.

**Comment by ganderzz** [comment]
@thisis-Shitanshu Definitely. I have a branch out there that *partially* implements Typescript, but there are still quite a few build errors. Feel free to take that branch over, or use it as a base to contribute!

**Comment by thisis-Shitanshu** [comment]
@ganderzz Great! I am starting working from the branch right away. I will reach out if I need your help somewhere and notify progress.

**Comment by thisis-Shitanshu** [comment]
PR #117 
Solves the error with the tests.
