### ISSUE TITLE
Calling multiple functions when scrolling

### ISSUE THREAD

**Issue by newyork-anthonyng** [ganderzz/react-scroll-to#11]
Please see this [CodeSandbox example](https://codesandbox.io/s/6rp43x7n3) where I'm trying to `console.log something` when I scroll on the page. You can imagine use cases where a user might want to do other things, such as call Redux actions, click tracking, etc.

Because the `handleScroll` function returns a function ([see here](https://github.com/ganderzz/react-scroll-to/blob/master/src/index.jsx#L14-L16)), I have to invoke the function like so:

```js
console.log("You scrolled!");
scroll(0, 500)();
```

Do you think it'd be a cleaner API if the `handleScroll` function didn't return a function, but rather invoked it? This way, the user could just do:

```js
console.log("You scrolled!");
scroll(0, 500);
```

This seems more intuitive to me, but would be a breaking change.

**Comment by ganderzz** [comment]
@newyork-anthonyng Sure. My use-case for this component mirrors the examples `<Com onClick={scroll(0, 0)}`, but I can see how it'd be more user friendly to not have to invoke the function twice.

I'll push the change out, and we'll mark the next release as being breaking.
