### ISSUE TITLE
smooth: true animation not working on Safari

### ISSUE THREAD

**Issue by cloobfm** [ganderzz/react-scroll-to#120]
**Describe the bug**
Animation does not currently work in Safari.  Scrolling works correctly to move to the position but immediately.

**To Reproduce**
1. Click on demo buttons
2. Scroll works but does not elegantly animate to target location.

**Expected behavior**
Chrome and Safari behaviors are different.  Chrome works as expected.

 - OS: OSX
 - Browser Chrome, Safari
 - Version Chrome 76.0.3809.100, Safari 12.1

Thx for your work.  This is the only plugin that solved my horizontal scrolling feature.

**Comment by seismicsix** [comment]
Just experienced the same issue on ios:

behavior: 'smooth'
is not supported in Edge, Safari or Mobile Safari - maybe a polyfill would solve the issue?

**Comment by seismicsix** [comment]
This worked for me...
https://www.npmjs.com/package/smoothscroll-polyfill

**Comment by cloobfm** [comment]
Thanks so much for pushing a fix.  I'm trying to install this commit directly via npm install github:ganderzz/react-scroll-to but it's not installing all of the files.  Is there a build you need to run, or can update the npm release package so I can update that way?

**Comment by ganderzz** [comment]
Sorry for the delay @cloobfm  ! 
I released 3.0.0-beta.2 so everyone can advantage of the fix, but if using a beta version is an issue check out just installing the polyfill above (https://www.npmjs.com/package/smoothscroll-polyfill)!

**Comment by cloobfm** [comment]
Thx so much!  Yeah had installed the polyfill for the time being.  I think this is resolved now.
