### ISSUE TITLE
[Question] : How would you use this in componentDidUpdate

### ISSUE THREAD

**Issue by alainpatrick** [ganderzz/react-scroll-to#124]
Sorry this isn't a feature request, although I'm not sure, it could be.

I'd like this function to auto execute (scroll to the top) when a page loads in componentDidUpdate or componentDidmount.

Thanks for your help.

**Comment by ganderzz** [comment]
Probably the best way to handle this right now is to use the HOC version of scroll-to!

```js
class MyComponent extends Component {
  componentDidMount() {
    this.props.scrollTo({ y: 0 });
 }
}

export ScrollToHOC(MyComponent);
```

Though future hooks implementation may make this even easier.

**Comment by alainpatrick** [comment]
Thanks a lot.
This solution didn't work for me certainly because I'm using Gatsby.
`componentDidMount() {
    ReactDOM.findDOMNode(this).scrollIntoView()
  }
`
ReactDOM solved my problem.
Again, thanks, I appreciate you for taking the time to help me out.
