### ISSUE TITLE
3.0.0 release in NPM is missing (Typscript-)types

### ISSUE THREAD

**Issue by Reggino** [ganderzz/react-scroll-to#126]
**Describe the bug**
3.0.0 release in NPM is missing (Typscript-)types

**To Reproduce**
```
npm install react-scroll-to@3
```
or
```
yarn add react-scroll-to@3
```

**Expected behavior**
A working version in my typescript-project, but Typescript can't find types. They are missing.

**Comment by ganderzz** [comment]
Looking into the missing types, thanks for the heads up @Reggino  !

**Comment by ganderzz** [comment]
3.0.0-beta.6 fixes the issue!
