### ISSUE TITLE
Instant props children error

### ISSUE THREAD

**Issue by resistorsoftware** [ganderzz/react-scroll-to#131]
I have an ES6 library called Polaris. I want to scroll to references. So I have my reference node. 

  "react-scroll-to": "^3.0.0-beta.6",

I import the ScrollTo component from the library, and then wrapped my list in a ScrollTo but this immediately threw errors. What am I doing wrong? 

import { ScrollTo } from "react-scroll-to";
 
and in my export default function App

     <Card>
            <ScrollTo>
              <ResourceList/>
            </ScrollTo>
      </Card>

generates TypeError: this.props.children is not a function

Sorry for not being more technical, but I am not sure what that means.

**Comment by ganderzz** [comment]
Hey @resistorsoftware ! 

ScrollTo is a [RenderProp](https://reactjs.org/docs/render-props.html) component, so its expecting a function as a child to access the scroll property.

ie.

```js
 <Card>
        <ScrollTo>
          {({ scroll }) => <ResourceList scroll={scroll} />}
        </ScrollTo>
  </Card>
```
