### ISSUE TITLE
Smooth scrolling doesn`t work in safari

### ISSUE THREAD

**Issue by laizeh** [ganderzz/react-scroll-to#137]
**Describe the bug**

code :
```javaScript
 const scrollToText = () => {
    scrollTo({ behavior: 'smooth', top: window.outerHeight });
  }

...
<div onClick={()=>scrollToText()} className="bottom down-arrow">
                <Icon
                  name="angle double down"
                  style={{ fontSize: '2rem' }}
                ></Icon>
button
</div>
```
When you press the button in Safari Browser,smooth scrolling doesn`t work 

But it can work properly in Chrome.

**Expected behavior**
it works

 - OS: MacOS 11.2
 - Browser: Safari 14.0.3 (16610.4.3.1.4)
 - Version: ^3.0.0-beta.4

**Comment by ganderzz** [comment]
Hey @laizeh, were you able to figure this out?
