### ISSUE TITLE
Add Linting

### ISSUE THREAD

**Issue by ganderzz** [ganderzz/react-scroll-to#19]
It'd be great to add linting to keep future contributions in a consistent style. Let's look at using [prettier](https://github.com/prettier/prettier).

A second part of this issue would be some kind of enforcement, which could tie into some kind of CI tool. Additionally, we could use a git pre-commit check.. I'm thinking [Husky](https://www.npmjs.com/package/husky), that would check both unit tests and linting.

**Comment by UmenR** [comment]
@ganderzz  I'd like to try and work on this , but  before that a bit of a clarification as to what options should be used and if it would suffice to only format all .js and .jsx files in the src folder during the pre-commit check.

**Comment by ganderzz** [comment]
@UmenR Go for it! Yes, just checking the formatting of all `.js` and `.jsx` in `src/` would work great.

The [AirBnB](https://github.com/airbnb/javascript) is generally my go-to linting style. So if we can use their config, that would be the best route!

**Comment by UmenR** [comment]
Hey @ganderzz i have implemented prettier do you want me to run it on the two jsx files in the src/ folder before submitting the PR ?

**Comment by ganderzz** [comment]
@UmenR 😁 Sweet! Yeah, let's apply the prettier styling to both the `jsx` files.

**Comment by ganderzz** [comment]
Resolved: #24 !!
