### ISSUE TITLE
Suggestion: Render props via render prop

### ISSUE THREAD

**Issue by JikkuJose** [ganderzz/react-scroll-to#3]
Hey, what do you think about adding `render` prop to the component for the **render props** pattern?

Say:

```js
<ScrollTo render={
 (scroll) => (
    <a onClick={scroll(0, 500)}>
      Scroll to Bottom
    </a>
  } 
/>
```

**Comment by ganderzz** [comment]
Sure, it's a use-case I could see being a benefit! Want to submit a pull request @JikkuJose?

**Comment by JikkuJose** [comment]
Great, will give a PR!

**Comment by newyork-anthonyng** [comment]
@JikkuJose I've generally seen components either use the `render` or `children` prop for rendering children, but never both. I'm trying to understand what the benefit of having both of them would be?

And what would happen if a user provided both props with an `argument`, like so:
```jsx
<ScrollTo render={
    (firstScroll) => <a onClick={() => firstScroll(0, 500)}>First</a>
  }
>
  {
    (secondScroll) => <a onClick={() => secondScroll(0, 500)}>Second</a>
  }
</ScrollTo>
```

Would we render both children? In that case, which goes first?
Or would the `render` prop have priority over the `children` prop if present? This might be more complicated than it needs to be.

**Comment by ganderzz** [comment]
@newyork-anthonyng Valid point, I wasn't even thinking of that. The main plus I can see is that having a render prop could be more clean, as it doesn't have the trailing `</ScrollTo>`, and `{ .. }` as a child.

Unless we can find a clean way, I'd rather keep it as only a child prop to reduce the complexity. Thoughts?

**Comment by newyork-anthonyng** [comment]
@ganderzz Agreed. I think we should choose one or the other to reduce the complexity. I think the `child prop` is good 👍

**Comment by JikkuJose** [comment]
There is a fundamental issue with child props despite its popularity & simplicity: the name of the function is `children` & it isn't clear when you have actually provide a function instead of a component as intended.

**Comment by ganderzz** [comment]
Open to criticism, but should it matter if a function or component is passed as `children`? The intent of `<ScrollTo>` is the relieve the children of scrolling logic. So, maybe we can handle both cases.

If `children` is a function, we treat everything the same.
```jsx
<ScrollTo>
{(scroll) => (
   <button onClick={() => scroll(0, 0)}>Click</button>
)}
</ScrollTo>
```

But if `children` is a component, or array of components, inject the scroll function prop. (This can be though of wrapping every child in ScrollToHOC). Injecting props to every component could get costly if we go all the way down the tree to sub-children, and sub-sub-children. So I suggest we only inject `props.scroll` to the immediate children, then let the consuming component control if `scroll` gets passed down further.

**Parent:** 
```jsx
<ScrollTo>
    <MyButton />
</ScrollTo>
```
**MyButton:**
```jsx
function MyButton(props) {
   const { scroll, ...other } = props;
   return (
      <button onClick={() => scroll(0, 0)} {...other}>
          Click
     </button>
   );
}
```

**Comment by JikkuJose** [comment]
But wasn't render props intended to replace HOCs?

Btw, just to confirm this cannot scroll contents inside a div but only can do it with window right?

**Comment by ganderzz** [comment]
@JikkuJose Maybe? It seems to React community is moving more towards render props, but HOC's have their place. I'd be open to see how people use React-Scroll-To, and adapt it accordingly.

Yes, ScrollTo only supports `window`, but that's an excellent point! I'll open an issue to discuss scrolling in other containers.

**Comment by JikkuJose** [comment]
@ganderzz didn't meant to bad mouth HoCs but somehow I am sold to render props after listening to a [talk](https://www.youtube.com/watch?v=BcVAq3YFiuc) by Michael Jackson.

Have already commented on the issue, but I wonder whether its even possible!

**Comment by ganderzz** [comment]
@JikkuJose Definitely on-board with render props (Michael Jackson sold me also)!

Let's keep to the discussion of a `render prop` in addition to `children render prop`. Unless we find a clean solution to the issues @newyork-anthonyng proposed, we should stick to just using the `child prop` as a function. I want to keep a small API footprint, so the less special cases, the better.

**Comment by JikkuJose** [comment]
@ganderzz cool!

**Comment by newyork-anthonyng** [comment]
@ganderzz @JikkuJose 👍 Can we close this issue?

**Comment by ganderzz** [comment]
Closing the issue for now.
