### ISSUE TITLE
v1.1.1 is broken: "scrollById" is not a function

### ISSUE THREAD

**Issue by newyork-anthonyng** [ganderzz/react-scroll-to#42]
### Issue

The second parameter, `scrollById`, is undefined. I believe this is because the wrong build was published to npm.

### Expected Behavior

The second parameter, `scrollById`, should be defined.

### Steps to Reproduce

Take a look at this [CodeSandbox demo](https://codesandbox.io/s/5wm7qolrmp). Notice how the `scrollById` is `undefined`.

### Recommendations
I think that we should change how we are saving our bundles. Currently, we have to manually run the build and commit it to Github. Instead, I think we should:
1. Add `dist` to our `.gitignore` file
2. Update our `package.json` so that the `dist` directory will be included when `react-scroll-to` is installed as a dependency ([see npm documentation](https://docs.npmjs.com/files/package.json#files)).
```json
// package.json
{
  "files": ["dist"]
}
```

**Comment by ganderzz** [comment]
@newyork-anthonyng Whops! Agreed, we need a better way of deploying scroll-to. Generally I've just added the dist bundle to Github, so this will be new for me. Adding `"files"` to `package.json`, how does it know how to get the dist files? Wouldn't it still have to be built beforehand?

I'm guessing we might have to use a prepublish script, something like `prepublishOnly`? (https://docs.npmjs.com/misc/scripts)
