### ISSUE TITLE
Update CodeSandbox examples

### ISSUE THREAD

**Issue by newyork-anthonyng** [ganderzz/react-scroll-to#43]
I wanted to update the CodeSandbox examples that we currently have.

I was thinking of including two different demos. I tried putting everything into one `CodeSandbox` example, but I felt like it was looking very intimidating to new users.

* One that just shows off using the `<ScrollTo />` component (https://codesandbox.io/s/yqlj0yjr41). 
* Another that shows off using the `<ScrollArea />` component (https://codesandbox.io/s/5wm7qolrmp). 

Let me know what you think; I can update the `README.md` to use these two demos.

**Note that the second demo does not work because of issue #42.**

**Comment by ganderzz** [comment]
I dig it, sounds like a good path to go with these demos. Break them up into bite-sized chunks.

I'll work on republishing v1.1.1 so we can get the examples out.
