### ISSUE TITLE
Support for smooth scrolling

### ISSUE THREAD

**Issue by BilalBudhani** [ganderzz/react-scroll-to#48]
Hi there, 

First of all, Thanks for providing us with a simple scrolling implementation. I implemented this in a project and it worked like a charm. 

I was wondering if there is a roadmap to supporting smooth scrolling. If no, then, can have a discussion around supporting it?

**Comment by ganderzz** [comment]
Thanks @BilalBudhani !

There has been some thought around smooth scrolling, but nothing official or on the roadmap. I think it would be a good addition to add an additional argument to `scrollTo` and `scrollToById` to add this. 

Example:
[smooth scroll](https://css-tricks.com/snippets/jquery/smooth-scrolling/)

**Comment by ganderzz** [comment]
#56
