### ISSUE TITLE
Add ScrollArea Typescript definitions

### ISSUE THREAD

**Issue by cjwillis809** [ganderzz/react-scroll-to#70]
Hello, 

I am looking to leverage this library for one of my projects but noticed that the ScrollArea component is not supported in Typescript as of now. Is there a plan to create a definition for this? It would be great if this could work with Typescript.

Thanks

**Comment by ganderzz** [comment]
@cjwillis809 Definitely, I'll look into adding a typedef for it!

**Comment by ganderzz** [comment]
A type definition for `<ScrollArea/>` has been deployed under v1.2.3

**Comment by cjwillis809** [comment]
Thank you!
