### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by newyork-anthonyng** [ganderzz/react-scroll-to#8]
@ganderzz Great work on this project!

I noticed there weren't any unit tests on `react-scroll-to` yet. Let me know if we should include it; I can create a PR 👍

**Comment by ganderzz** [comment]
@newyork-anthonyng Thanks!

Definitely need unit tests. That was next on my todo-list, but feel free to make a PR for it! Open to suggestions, but I'm a fan of [Jest](https://facebook.github.io/jest/).

**Comment by ganderzz** [comment]
Added Jest as the framework for unit tests with some primitive tests.

Leaving this issue open, as we could definitely use more unit tests!

**Comment by newyork-anthonyng** [comment]
Awesome. I added some more unit tests in #18. 

I'm wondering if we should add a `coverage` threshold ([see more](https://facebook.github.io/jest/docs/en/configuration.html#coveragethreshold-object))?

**Comment by ganderzz** [comment]
I'd be in favor of adding a coverage threshold. Since this library is pretty small, a high coverage shouldn't be hard to hit.
Ideally we'd have a 100% coverage, but for now a 80-95% would be a good target until we build up tests.
