### ISSUE TITLE
window is not defined error during SSR

### ISSUE THREAD

**Issue by tim-soft** [ganderzz/react-scroll-to#81]
**Describe the bug**
Trying out this library in an isomorphic app, during a server-side render, this library throws a reference error that the window is not defined.

**Expected behavior**
Add a sanity check to see if the window exists yet before trying to initialize anything against the window object.

ref to similar solution: https://github.com/fisshy/react-scroll/pull/209

**Comment by ganderzz** [comment]
@tim-soft Thanks for bringing this up! It seems that we may have a problem with Webpack's bundling using UMD builds (https://github.com/webpack/webpack/issues/6522).

I'll push up a fix for this soon 👍

**Comment by ganderzz** [comment]
Merged and published (2.0.1) !

**Comment by thongncvn** [comment]
@ganderzz This problem appears again for NextJS...

**Comment by enesozturk** [comment]
Hi! This problem still appears.
react-scroll-to@^3.0.0-beta.2
next@^9.0.5

**Comment by ganderzz** [comment]
Looking into it, thanks!

I'm assuming this may be due to the polyfill included in the beta.

**Comment by ganderzz** [comment]
Try 3.0.0-beta.3 !

**Comment by enesozturk** [comment]
I tried 3.0.0-beta.3 but problem still exist. Here is my screenshots below. I do not use Typescript in my project. 
<img width="798" alt="Screen Shot 2019-10-25 at 12 42 25" src="https://user-images.githubusercontent.com/19428358/67561429-804ea880-f725-11e9-87be-21a1b1c36527.png">
<img width="853" alt="Screen Shot 2019-10-25 at 12 43 50" src="https://user-images.githubusercontent.com/19428358/67561430-804ea880-f725-11e9-90ee-9553acabee60.png">

**Comment by oyeanuj** [comment]
@ganderzz Any thoughts on this one?

**Comment by ganderzz** [comment]
@oyeanuj The issue was the polyfill being included for smooth scroll. Removed it, and now consumers will now need to include it. Should fix the issue! Try now.

3.0.0-beta.4
