### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Real001** [ganderzz/react-scroll-to#84]
When using a component: 
![image](https://user-images.githubusercontent.com/13777961/48689340-9e9a5300-ebfc-11e8-8d19-cc9e4dd4f821.png)

**Comment by ganderzz** [comment]
Hey @Real001,
can you provide some sample code, and steps to reproduce this error?

**Comment by mahathun** [comment]
i get the same error, most likely this will be some dependancy issue, 
i just ran 
`yarn add react-scroll-to` 
in the terminal and then imported ScrollTo in the file
`import { ScrollTo } from "react-scroll-to";`

**Comment by ganderzz** [comment]
Odd.
I tried installing react-scroll-to as a dependency for create-react-app, and I'm not seeing any errors.
What browser is this being testing on?
Can you provide sample code/project? (https://codesandbox.io/s/o5v2y5mk9q)

**Comment by mahathun** [comment]
@ganderzz hey, I added my dependencies to the package.json, and now you'll be able to see the error.
https://codesandbox.io/s/9qyljzwjkr

**Comment by ganderzz** [comment]
This seems to be a React version issue--which I'm guessing comes from that we're using `React.createContext()`. Upgrading React to the latest version (16.6) fixes the issue. (https://codesandbox.io/s/1y0zkzv88l)

If it's just the context cause the issue it seems like a trivial fix we can get in. I'll be away for a few days so I'm open for PR's--if not I'll try to get a fix out sometime this week!

**Comment by ganderzz** [comment]
This has been fixed and deployed in v2.0.2 !

(https://codesandbox.io/s/n0p4j286nj)
