### ISSUE TITLE
Move example into CodeSandbox

### ISSUE THREAD

**Issue by newyork-anthonyng** [ganderzz/react-scroll-to#9]
I think moving the `example` we have into [CodeSandbox](https://www.codesandbox.io) would be great.

People would not have to commit to downloading this repository just to see if it works. Also, I had some issues setting up the `example` directory. On my machine, it wasn't just as simple as running `npm install` and `npm run build`. I was getting errors that `react` didn't exist, and was too lazy to debug.

`CodeSandbox` would solve all of that. Let me know if this makes sense and I can create a PR.

**Comment by ganderzz** [comment]
@newyork-anthonyng Great idea. I wasn't a fan of having the examples folder embeded in the repo, but it provided a test area and gave users a way to interact.

Feel free to make a PR to move the example to to CodeSandbox, and remove the examples folder.

**Comment by newyork-anthonyng** [comment]
FYI. I updated the CodeSandbox example to take into account the breaking change in `1.0.3`.
