### ISSUE TITLE
v2.0.3 & v2.0.4 are broken

### ISSUE THREAD

**Issue by ggascoigne** [ganderzz/react-scroll-to#95]
Neither of these versions when downloaded from npmjs.org have a dist folder in the package.  Looks like v2.0.2 loads correctly.

**Comment by ganderzz** [comment]
@ggascoigne Sorry about that--must of messed up the deployment. I'll get a version released with the correct files.

**Comment by ganderzz** [comment]
Fixed with v2.0.5
